export const types = [{
    caption: 'uint64_t',
    value: 'uint64_t',
    meta: 'keyword'
}, {
    caption: 'int64_t',
    value: 'int64_t',
    meta: 'keyword'
}, {
    caption: 'uint32_t',
    value: 'uint32_t',
    meta: 'keyword'
}, {
    caption: 'int32_t',
    value: 'int32_t',
    meta: 'keyword'
}, {
    caption: 'uint16_t',
    value: 'uint16_t',
    meta: 'keyword'
}, {
    caption: 'int16_t',
    value: 'int16_t',
    meta: 'keyword'
}, {
    caption: 'uint8_t',
    value: 'uint8_t',
    meta: 'keyword'
}, {
    caption: 'int8_t',
    value: 'int8_t',
    meta: 'keyword'
}]
