export const types = [{
    value: 'uint64_t',
    meta: 'keyword'
}, {
    value: 'int64_t',
    meta: 'keyword'
}, {
    value: 'uint32_t',
    meta: 'keyword'
}, {
    value: 'int32_t',
    meta: 'keyword'
}, {
    value: 'uint16_t',
    meta: 'keyword'
}, {
    value: 'int16_t',
    meta: 'keyword'
}, {
    value: 'uint8_t',
    meta: 'keyword'
}, {
    value: 'int8_t',
    meta: 'keyword'
}]

export const apis = [{
    value: 'current_receiver',
    meta: 'gxc_api',
    comments: 'haheheheheh'
}, {
    value: 'get_action_asset_id',
    meta: 'gxc_api'
}, {
    value: 'get_action_asset_id',
    meta: 'gxc_api'
}, {
    value: 'get_action_asset_amount',
    meta: 'gxc_api'
}, {
    value: 'withdraw_asset',
    meta: 'gxc_api'
}, {
    value: 'get_balance',
    meta: 'gxc_api'
}, {
    value: 'sha256',
    meta: 'gxc_api'
}, {
    value: 'sha512',
    meta: 'gxc_api'
}, {
    value: 'ripemd160',
    meta: 'gxc_api'
}, {
    value: 'verify_signature',
    meta: 'gxc_api'
}, {
    value: 'get_head_block_id',
    meta: 'gxc_api'
}, {
    value: 'get_head_block_num',
    meta: 'gxc_api'
}, {
    value: 'get_head_block_time',
    meta: 'gxc_api'
}, {
    value: 'get_trx_sender',
    meta: 'gxc_api'
}, {
    value: 'get_account_id',
    meta: 'gxc_api'
}, {
    value: 'get_asset_id',
    meta: 'gxc_api'
}, {
    value: 'graphene_assert',
    meta: 'gxc_api'
}, {
    value: 'graphene_assert_message',
    meta: 'gxc_api'
}, {
    value: 'print',
    meta: 'gxc_api'
}]
